### ISSUE TITLE
日期格式问题

### ISSUE THREAD

**Issue by sunyatas** [Othershe/CalendarView#1]
获取到的时间格式是1900.1.1，可以设置成1900.01.01这种吗

**Comment by liunian1010** [comment]
这个可以自己做一下字符串分割然后拼装下就可以了嘛

**Comment by 15896910112** [comment]
你好，请问怎么在日期下面加图片？ 就是不符合一些条件的日期下面加个 x  的图片！  如果可以的话能加下我的QQ吗？  320884085   谢谢
