### ISSUE TITLE
只设置双选日期，需要怎么控制呢？

### ISSUE THREAD

**Issue by Achenglove** [Othershe/CalendarView#2]

**Comment by Othershe** [comment]
oh，这个功能目前没有，但是实现也不难

**Comment by Achenglove** [comment]
可以提供点思路吗

**Comment by Othershe** [comment]
MonthView类中有如下代码片段，可尝试控制chooseDays的大小来实现
![default](https://user-images.githubusercontent.com/11371934/29013586-7db24a50-7b76-11e7-800a-276a53a93cdc.PNG)

**Comment by Achenglove** [comment]
可以了，谢谢哈

**Comment by Othershe** [comment]
不客气！

**Comment by Achenglove** [comment]
还有一个问题就是，怎么缩小日历行与行之间，列与列之间的那个距离呢？

**Comment by Othershe** [comment]
xml中CalendarView的宽度小了，间距也就小了

**Comment by Achenglove** [comment]
多选的时候怎么允许选择当天之前的时间呢？

**Comment by Othershe** [comment]
看文档吧

**Comment by crazeluo** [comment]
> 
> 
> 可以了，谢谢哈

前辈，这个是怎么实现双选的？
