### ISSUE TITLE
关于MonthView高度设置的问题

### ISSUE THREAD

**Issue by qq156c** [Othershe/CalendarView#3]
我看到您这边是直接把item的高度设置为整体宽度的1/6 这样子的话,在不显示农历的情况下,日历会显得太高而占用掉大半的屏幕,如果我只想把屏幕上半部分显示日历的话,不得不缩减CalendarView的宽度,请问能否考虑把高度设小一点呢

**Comment by Othershe** [comment]
最近打算重构一下，会考虑的哦
